# Generated by Django 6.0.6 on 2026-07-07 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude for distance calculations', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude for distance calculations', null=True)),
                ('phone', models.CharField(blank=True, help_text='Fallback contact number', max_length=15, null=True)),
                ('medical_disease', models.TextField(blank=True, help_text='Any past or chronic medical illnesses', null=True)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('blood_report', models.FileField(blank=True, help_text='Recent pathology test files', null=True, upload_to='reports/')),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('donation_count', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True, help_text='Is the donor ready to donate now?')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LEAVE', 'On Leave'), ('BUSY', 'Busy')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Profile',
                'verbose_name_plural': 'Donor Profiles',
            },
        ),
    ]
