# Generated by Django 6.0.7 on 2026-07-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='average_response_time',
            field=models.FloatField(default=15.0, help_text='Average response time in minutes'),
        ),
        migrations.AddField(
            model_name='donor',
            name='cancellation_count',
            field=models.IntegerField(default=0, help_text='Total cancelled responses'),
        ),
        migrations.AddField(
            model_name='donor',
            name='trust_score',
            field=models.FloatField(default=85.0, help_text='AI Donor Trust Score (0-100)'),
        ),
        migrations.AddField(
            model_name='donor',
            name='verification_status',
            field=models.BooleanField(default=True, help_text='Is the donor account identity verified?'),
        ),
    ]
