# Generated by Django 6.0.7 on 2026-07-31 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital / Clinic'), ('BLOOD_BANK', 'Blood Bank')], default='HOSPITAL', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('helpline_phone', models.CharField(max_length=15)),
                ('operating_hours', models.CharField(default='24/7 Emergency Open', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('stock_a_positive', models.IntegerField(default=10)),
                ('stock_a_negative', models.IntegerField(default=3)),
                ('stock_b_positive', models.IntegerField(default=12)),
                ('stock_b_negative', models.IntegerField(default=4)),
                ('stock_o_positive', models.IntegerField(default=20)),
                ('stock_o_negative', models.IntegerField(default=5)),
                ('stock_ab_positive', models.IntegerField(default=6)),
                ('stock_ab_negative', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital & Blood Bank Facility',
                'verbose_name_plural': 'Hospitals & Blood Banks Facilities',
            },
        ),
    ]
