# Generated by Django 6.0.7 on 2026-08-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_hospitalbloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_a_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_a_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_ab_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_ab_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_b_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_b_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_o_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbloodbank',
            name='stock_o_positive',
            field=models.IntegerField(default=0),
        ),
    ]
