# Generated by Django 6.0.7 on 2026-07-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_make_normal_users_dual_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('HOSPITAL', 'Hospital'), ('BLOOD_BANK', 'Blood Bank')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('RECEIVER', 'Receiver'), ('HOSPITAL', 'Hospital'), ('BLOOD_BANK', 'Blood Bank')], default='RECEIVER', max_length=20),
        ),
    ]
