# Generated by Django 6.0.7 on 2026-08-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('detected_language', models.CharField(default='en-US', max_length=20)),
                ('extracted_blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('extracted_city', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_priority', models.CharField(choices=[('CRITICAL', '🔴 Critical'), ('HIGH', '🟠 High'), ('NORMAL', '🟢 Normal')], default='HIGH', max_length=20)),
                ('extracted_required_time', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField(default=0.9)),
                ('field_confidences', models.JSONField(default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Request Log',
                'verbose_name_plural': 'Voice Request Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
