# Generated by Django 6.0.6 on 2026-07-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('blood_group', models.CharField(max_length=5)),
                ('units_required', models.IntegerField(default=1)),
                ('emergency_level', models.CharField(choices=[('CRITICAL', 'Critical (Immediate)'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DONOR_ON_THE_WAY', 'Donor On The Way'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.TextField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations_assigned', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
