# Generated by Django 6.0.7 on 2026-07-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('units', models.IntegerField(default=1)),
                ('reason', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requests.emergencyrequest')),
            ],
            options={
                'db_table': 'request_responses',
            },
        ),
    ]
